# Generated by Django 5.2.6 on 2026-08-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20),
        ),
    ]
