# Generated by Django 5.1.6 on 2026-07-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_course_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiomodule',
            name='question_audio_file',
            field=models.FileField(blank=True, upload_to='question_audio_modules/'),
        ),
        migrations.AddField(
            model_name='audiomodule',
            name='question_duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiomodule',
            name='question_text',
            field=models.TextField(blank=True),
        ),
    ]
