# Generated by Django 5.2.15 on 2026-08-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_learningobject_section_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
