# Generated by Django 5.2.4 on 2026-07-09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_audiomodule_question_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outlinenode",
            name="status",
        ),
        migrations.DeleteModel(
            name="AudioModule",
        ),
        migrations.DeleteModel(
            name="PageImage",
        ),
        migrations.DeleteModel(
            name="LessonPage",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
    ]
