# Generated by Django 5.2.4 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0005_learning_material_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseoutline",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="courseoutline",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
