# Generated by Django 5.2.15 on 2026-09-03 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_learningmaterial_file_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='source_block_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='source_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='source_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LearningObjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outline_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_object_groups', to='lessons.outlinenode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='learningobject',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_objects', to='lessons.learningobjectgroup'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('source_block_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_excerpt', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lessons.learningmaterial')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionLearningObjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=0.0)),
                ('method', models.CharField(default='layout_tfidf', max_length=100)),
                ('is_primary', models.BooleanField(default=True)),
                ('learning_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='lessons.learningobject')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_object_links', to='lessons.question')),
            ],
            options={
                'ordering': ['-is_primary', '-relevance_score', 'id'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='learning_objects',
            field=models.ManyToManyField(related_name='questions', through='lessons.QuestionLearningObjectLink', to='lessons.learningobject'),
        ),
        migrations.AddConstraint(
            model_name='questionlearningobjectlink',
            constraint=models.UniqueConstraint(fields=('question', 'learning_object'), name='unique_question_learning_object_link'),
        ),
        migrations.AddConstraint(
            model_name='questionlearningobjectlink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('question',), name='unique_primary_learning_object_per_question'),
        ),
    ]
