# Generated by Django 5.2.15 on 2026-07-12 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_courseoutline_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('semantic_similarity', models.FloatField(blank=True, null=True)),
                ('outline_order_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_edges', to='lessons.coursegroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_prerequisite_edges', to='lessons.outlinenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_prerequisite_edges', to='lessons.outlinenode')),
            ],
            options={
                'ordering': ['source__order', 'target__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'source', 'target'), name='unique_outline_prerequisite_edge'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='outline_edge_source_not_target'), models.CheckConstraint(condition=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='outline_edge_score_between_0_and_1'), models.CheckConstraint(condition=models.Q(('semantic_similarity__isnull', True), models.Q(('semantic_similarity__gte', 0.0), ('semantic_similarity__lte', 1.0)), _connector='OR'), name='outline_edge_semantic_similarity_between_0_and_1'), models.CheckConstraint(condition=models.Q(('outline_order_score__isnull', True), models.Q(('outline_order_score__gte', 0.0), ('outline_order_score__lte', 1.0)), _connector='OR'), name='outline_edge_order_score_between_0_and_1')],
            },
        ),
    ]
