# Generated by Codex on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_outlineedge"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningmaterial",
            name="outline_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="lessons.outlinenode",
            ),
        ),
    ]
