# Generated by Django 5.2.15 on 2026-07-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_learningmaterial_outline_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='module_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_materials', to='lessons.outlinenode'),
        ),
        migrations.CreateModel(
            name='ExtractedConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_title', models.CharField(max_length=255)),
                ('normalized_title', models.CharField(editable=False, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_concepts', to='lessons.coursegroup')),
                ('module_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_concepts', to='lessons.outlinenode')),
            ],
            options={
                'ordering': ['module_node__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('source_excerpt', models.TextField(blank=True)),
                ('first_appearance_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_sources', to='lessons.learningmaterial')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='lessons.extractedconcept')),
            ],
            options={
                'ordering': ['first_appearance_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConceptPrerequisiteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('semantic_similarity', models.FloatField(blank=True, null=True)),
                ('instructional_order_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_prerequisite_edges', to='lessons.coursegroup')),
                ('module_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_prerequisite_edges', to='lessons.outlinenode')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_prerequisite_edges', to='lessons.extractedconcept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_prerequisite_edges', to='lessons.extractedconcept')),
            ],
            options={
                'ordering': ['source__order', 'target__order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='extractedconcept',
            constraint=models.UniqueConstraint(fields=('course', 'module_node', 'normalized_title'), name='unique_extracted_concept_normalized_title_per_module'),
        ),
        migrations.AddConstraint(
            model_name='extractedconcept',
            constraint=models.CheckConstraint(check=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0.0), ('confidence__lte', 1.0)), _connector='OR'), name='extracted_concept_confidence_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='conceptsource',
            constraint=models.UniqueConstraint(fields=('concept', 'learning_material', 'page_number', 'section_title', 'source_excerpt'), name='unique_concept_source_reference'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.UniqueConstraint(fields=('course', 'module_node', 'source', 'target'), name='unique_concept_prerequisite_edge'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(check=models.Q(('source', models.F('target')), _negated=True), name='concept_edge_source_not_target'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='concept_edge_score_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(check=models.Q(('semantic_similarity__isnull', True), models.Q(('semantic_similarity__gte', 0.0), ('semantic_similarity__lte', 1.0)), _connector='OR'), name='concept_edge_semantic_similarity_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(check=models.Q(('instructional_order_score__isnull', True), models.Q(('instructional_order_score__gte', 0.0), ('instructional_order_score__lte', 1.0)), _connector='OR'), name='concept_edge_instructional_order_between_0_and_1'),
        ),
    ]
