# Generated by Django 5.2.15 on 2026-09-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_questionlearningobjectlink_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseoutline',
            options={'ordering': ['uploaded_at', 'id']},
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='lessons.coursegroup'),
        ),
    ]
