# Generated by Django 5.2.15 on 2026-07-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_learningmaterial_module_node_extractedconcept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='generated_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
