# Generated by Django 5.2.6 on 2026-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_question_authoring_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinenode',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlinenode',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
