# Generated by Django 5.2.15 on 2026-07-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_learningmaterial_generated_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleConceptDAGState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module_node__order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='conceptprerequisiteedge',
            name='dependency_cue_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptprerequisiteedge',
            name='source_order_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptprerequisiteedge',
            name='title_overlap_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(condition=models.Q(('dependency_cue_score__isnull', True), models.Q(('dependency_cue_score__gte', 0.0), ('dependency_cue_score__lte', 1.0)), _connector='OR'), name='concept_edge_dependency_cue_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(condition=models.Q(('source_order_score__isnull', True), models.Q(('source_order_score__gte', 0.0), ('source_order_score__lte', 1.0)), _connector='OR'), name='concept_edge_source_order_between_0_and_1'),
        ),
        migrations.AddConstraint(
            model_name='conceptprerequisiteedge',
            constraint=models.CheckConstraint(condition=models.Q(('title_overlap_score__isnull', True), models.Q(('title_overlap_score__gte', 0.0), ('title_overlap_score__lte', 1.0)), _connector='OR'), name='concept_edge_title_overlap_between_0_and_1'),
        ),
        migrations.AddField(
            model_name='moduleconceptdagstate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_dag_states', to='lessons.coursegroup'),
        ),
        migrations.AddField(
            model_name='moduleconceptdagstate',
            name='module_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concept_dag_state', to='lessons.outlinenode'),
        ),
        migrations.AddConstraint(
            model_name='moduleconceptdagstate',
            constraint=models.UniqueConstraint(fields=('course', 'module_node'), name='unique_module_concept_dag_state'),
        ),
    ]
