# Generated by Django 5.2.15 on 2026-07-17 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_moduleconceptdagstate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjectPrerequisiteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('semantic_similarity', models.FloatField(blank=True, null=True)),
                ('dependency_cue_score', models.FloatField(blank=True, null=True)),
                ('source_order_score', models.FloatField(blank=True, null=True)),
                ('title_overlap_score', models.FloatField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_object_prerequisite_edges', to='lessons.coursegroup')),
                ('module_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_object_prerequisite_edges', to='lessons.outlinenode')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_prerequisite_edges', to='lessons.learningobject')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_prerequisite_edges', to='lessons.learningobject')),
            ],
            options={
                'ordering': ['source__material_id', 'source__order', 'target__material_id', 'target__order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('course', 'module_node', 'source', 'target'), name='unique_learning_object_prerequisite_edge'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='learning_object_edge_source_not_target'), models.CheckConstraint(condition=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='learning_object_edge_score_between_0_and_1')],
            },
        ),
    ]
