# Generated by Django 5.2.17 on 2026-09-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_question_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='represented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='represents', to='lessons.learningobject'),
        ),
    ]
