# Generated by Django 5.2.15 on 2026-07-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_remove_non_milestone_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinenode',
            name='related_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
