# Generated by Django 5.2.17 on 2026-08-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_outlinenode_related_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='learningobject',
            name='section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='learningobject',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
