# Generated by Django 5.2.17 on 2026-09-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_learningobject_grouping_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='merged_from',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningobjectmatchsuggestion',
            name='candidate_extra_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningobjectmatchsuggestion',
            name='source_extra_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
