# Generated by Django 5.2.17 on 2026-09-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_merge_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningobject',
            name='merged_from',
        ),
    ]
