# Generated by Django 5.2.17 on 2026-10-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_drop_merged_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobject',
            name='kept_apart_from_section',
            field=models.BooleanField(default=False),
        ),
    ]
