# Generated by Django 5.2.17 on 2026-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_learningobject_kept_apart_from_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='teacher_edited',
            field=models.BooleanField(default=False),
        ),
    ]
