# Generated by Django 5.2.15 on 2026-10-04 15:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_reconcile_numbered_concept_parts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='coursegroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('created_by'), name='unique_course_title_per_creator_ci'),
        ),
    ]
