# Generated by Django 5.2.17 on 2026-10-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_reconcile_numbered_concept_parts'),
        ('lessons', '0021_question_teacher_edited'),
    ]

    operations = [
    ]
