# Generated by Django 5.2.17 on 2026-10-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_coursegroup_created_by_and_more'),
        ('lessons', '0022_merge_20261004_1813'),
    ]

    operations = [
    ]
