# Generated by Django 5.2.15 on 2026-07-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0009_alter_courseoutline_options_and_more'),
        ('question_generation', '0002_generationrun_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.OneToOneField(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_module', to='lessons.outlinenode')),
            ],
            options={
                'ordering': ['source__order', 'source__id'],
            },
        ),
        migrations.CreateModel(
            name='LessonNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_nodes', to='course.coursemodule')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_lesson_node', to='lessons.outlinenode')),
            ],
            options={
                'ordering': ['source__depth', 'source__order', 'source__id'],
            },
        ),
        migrations.CreateModel(
            name='LessonVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('NORMAL', 'Normal'), ('ELABORATED', 'Elaborated'), ('SIMPLIFIED', 'Simplified')], max_length=20)),
                ('narration', models.TextField()),
                ('audio_url', models.CharField(blank=True, max_length=255)),
                ('lesson_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='course.lessonnode')),
            ],
            options={
                'ordering': ['lesson_node_id', 'variant'],
                'unique_together': {('lesson_node', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='ModuleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_level', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('ANALYZE', 'Analyze')], max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_questions', to='course.lessonnode')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_generation.generatedquestion')),
            ],
            options={
                'ordering': ['lesson_node_id', 'bloom_level', 'order', 'id'],
                'unique_together': {('lesson_node', 'question')},
            },
        ),
    ]
