# Generated by Django 5.2.17 on 2026-08-06 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('lessons', '0009_alter_courseoutline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['source__order']},
        ),
        migrations.AlterModelOptions(
            name='lessonnode',
            options={'ordering': ['source__created_at']},
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='source',
            field=models.OneToOneField(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_module', to='lessons.outlinenode'),
        ),
        migrations.AlterField(
            model_name='lessonnode',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_lesson_node', to='lessons.learningmaterial'),
        ),
    ]
