# Generated by Django 5.2.17 on 2026-08-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_coursemodule_options_alter_lessonnode_options_and_more'),
        ('lessons', '0015_outlinenode_related_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvariant',
            name='learning_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='lessons.learningobject'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='lessonvariant',
            options={'ordering': ['learning_object_id', 'variant']},
        ),
        migrations.AlterModelOptions(
            name='modulequestion',
            options={'ordering': ['lesson_node_id', 'order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='lessonvariant',
            unique_together={('learning_object', 'variant')},
        ),
        migrations.RemoveField(
            model_name='modulequestion',
            name='bloom_level',
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='source',
            field=models.OneToOneField(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_package_module', to='lessons.outlinenode'),
        ),
        migrations.AlterField(
            model_name='lessonnode',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_package_lesson_node', to='lessons.learningmaterial'),
        ),
        migrations.AlterField(
            model_name='lessonvariant',
            name='variant',
            field=models.CharField(choices=[('ELABORATED', 'Elaborated'), ('SIMPLIFIED', 'Simplified')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='lessonvariant',
            name='lesson_node',
        ),
    ]
