# Generated by Django 5.2.15 on 2026-09-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_lessonvariant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvariant',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonvariant',
            name='generator_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lessonvariant',
            name='source_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
