# Generated by Django 5.2.17 on 2026-09-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_lessonvariant_generated_at_and_more'),
        ('lessons', '0015_learningobject_represented_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonvariant',
            name='assigned_by',
            field=models.CharField(choices=[('heuristic', 'Proposed by the readability heuristic'), ('teacher', 'Confirmed or corrected by a teacher')], default='heuristic', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonvariant',
            name='origin',
            field=models.CharField(choices=[('source_pdf', 'Text from a grouped source PDF'), ('generated', 'Generated by the adaptive variant model')], default='generated', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonvariant',
            name='source_learning_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_variants', to='lessons.learningobject'),
        ),
        migrations.AlterField(
            model_name='lessonvariant',
            name='variant',
            field=models.CharField(choices=[('ELABORATED', 'Elaborated'), ('SIMPLIFIED', 'Simplified'), ('EXTRA', 'Extra')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='lessonvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('variant', 'EXTRA'), _negated=True), fields=('learning_object', 'variant'), name='unique_primary_variant_slot'),
        ),
    ]
