# Generated by Django 5.2.17 on 2026-10-04 04:11

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the mobile lesson-package wrappers (moved out to be rebuilt).

    Children first so no foreign key is left pointing at a dropped table.
    """

    dependencies = [
        ('course', '0007_repair_cross_group_version_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleQuestion',
        ),
        migrations.DeleteModel(
            name='LessonNode',
        ),
        migrations.DeleteModel(
            name='CourseModule',
        ),
    ]
