# Generated by Django 5.2.17 on 2026-09-05 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0011_outlinenode_published_outlinenode_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerequisiteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(choices=[('title_reference', "Dependent text names the prerequisite's concept"), ('section_reference', "Dependent's section names the prerequisite's concept"), ('term_cooccurrence', 'Shared salient terms introduced by the prerequisite')], max_length=30)),
                ('weight', models.FloatField(default=1.0)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_edges', to='lessons.learningobject')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_edges', to='lessons.learningobject')),
            ],
            options={
                'ordering': ['dependent_id', '-weight', 'id'],
                'indexes': [models.Index(fields=['dependent'], name='learning_pa_depende_f5d06d_idx'), models.Index(fields=['prerequisite'], name='learning_pa_prerequ_497dd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('prerequisite', 'dependent', 'signal'), name='unique_prerequisite_edge_per_signal'), models.CheckConstraint(condition=models.Q(('prerequisite', models.F('dependent')), _negated=True), name='prerequisite_edge_must_not_be_self_loop')],
            },
        ),
    ]
