# Generated by Django 5.2.17 on 2026-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisiteedge',
            name='signal',
            field=models.CharField(choices=[('title_reference', "Dependent text names the prerequisite's concept"), ('section_reference', "Dependent's section names the prerequisite's concept"), ('term_cooccurrence', 'Shared salient terms introduced by the prerequisite'), ('chunk_continuation', 'Next part of a passage the chunker split')], max_length=30),
        ),
    ]
