# Generated by Django 5.2.17 on 2026-09-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0003_alter_prerequisiteedge_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisiteedge',
            name='source',
            field=models.CharField(choices=[('derived', 'Derived from text signals'), ('teacher', 'Added by a teacher')], db_index=True, default='derived', max_length=10),
        ),
    ]
