# Generated by Django 5.2.17 on 2026-09-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0005_alter_prerequisiteedge_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisiteedge',
            name='signal',
            field=models.CharField(choices=[('voted', 'Carried a majority of the derivation criteria'), ('chunk_continuation', 'Next part of a passage the chunker split'), ('teacher_authored', 'Added by a teacher during review')], max_length=30),
        ),
    ]
