# Generated by Django 5.2.17 on 2026-09-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0006_alter_prerequisiteedge_signal'),
        ('lessons', '0017_learningobject_grouping_content_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted by the criteria'), ('pending', 'Proposed, awaiting a teacher'), ('approved', 'Approved by a teacher'), ('rejected', 'Rejected by a teacher')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('derived', 'Derived by the criteria'), ('teacher', 'Decided by a teacher')], default='derived', max_length=10)),
                ('cross_section', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='lessons.learningobjectgroup')),
                ('outline_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_prerequisites', to='lessons.outlinenode')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='lessons.learningobjectgroup')),
            ],
            options={
                'ordering': ['outline_node_id', 'prerequisite_id', 'dependent_id'],
                'constraints': [models.UniqueConstraint(fields=('prerequisite', 'dependent'), name='unique_concept_prerequisite_pair'), models.CheckConstraint(condition=models.Q(('prerequisite', models.F('dependent')), _negated=True), name='concept_prerequisite_must_not_be_self_loop')],
            },
        ),
        migrations.CreateModel(
            name='LearningPathStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_steps', to='lessons.learningobjectgroup')),
                ('outline_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path_steps', to='lessons.outlinenode')),
            ],
            options={
                'ordering': ['outline_node_id', 'position'],
                'constraints': [models.UniqueConstraint(fields=('outline_node', 'position'), name='unique_learning_path_position'), models.UniqueConstraint(fields=('outline_node', 'concept'), name='unique_learning_path_concept')],
            },
        ),
    ]
