# Generated by Django 5.2.17 on 2026-09-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0007_concept_prerequisites_and_path_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrerequisiteEdge',
        ),
    ]
