# Generated by Django 5.2.17 on 2026-09-30 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_path', '0008_remove_prerequisite_edge'),
        ('lessons', '0019_drop_merged_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseConceptLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted by the criteria'), ('pending', 'Proposed, awaiting a teacher'), ('approved', 'Approved by a teacher'), ('rejected', 'Rejected by a teacher')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('derived', 'Derived by the criteria'), ('teacher', 'Decided by a teacher')], default='derived', max_length=10)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_concept_links', to='lessons.coursegroup')),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prerequisite_links', to='lessons.learningobjectgroup')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_dependent_links', to='lessons.learningobjectgroup')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prerequisite', 'dependent'), name='unique_course_concept_link')],
            },
        ),
    ]
