from django.db import models

from lessons.models import LearningObject


class LessonVariant(models.Model):
    VARIANTS = [
        ("ELABORATED", "Elaborated"),
        ("SIMPLIFIED", "Simplified"),
    ]

    class Origin(models.TextChoices):
        SOURCE_PDF = "source_pdf", "Text from a grouped source PDF"
        GENERATED = "generated", "Generated by the adaptive variant model"

    class AssignedBy(models.TextChoices):
        HEURISTIC = "heuristic", "Proposed by the readability heuristic"
        LLM_VALIDATED = "llm_validated", "Proposed by the LLM and validated by readability rules"
        TEACHER = "teacher", "Confirmed or corrected by a teacher"

    learning_object = models.ForeignKey(
        LearningObject,
        on_delete=models.CASCADE,
        related_name="variants",
    )
    variant = models.CharField(max_length=20, choices=VARIANTS)
    narration = models.TextField()
    audio_url = models.CharField(max_length=255, blank=True)
    source_fingerprint = models.CharField(max_length=64, blank=True)
    generator_model = models.CharField(max_length=100, blank=True)
    generated_at = models.DateTimeField(null=True, blank=True)
    origin = models.CharField(
        max_length=20,
        choices=Origin.choices,
        default=Origin.GENERATED,
    )
    # Which grouped object supplied this wording. Null for generated rows.
    source_learning_object = models.ForeignKey(
        LearningObject,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="supplied_variants",
    )
    assigned_by = models.CharField(
        max_length=20,
        choices=AssignedBy.choices,
        default=AssignedBy.HEURISTIC,
    )

    class Meta:
        ordering = ["learning_object_id", "variant"]
        constraints = [
            # An object has at most one simplified and one elaborated version.
            models.UniqueConstraint(
                fields=["learning_object", "variant"],
                name="unique_primary_variant_slot",
            ),
            models.CheckConstraint(
                condition=models.Q(variant__in=("SIMPLIFIED", "ELABORATED")),
                name="lessonvariant_active_variant",
            ),
        ]

    @property
    def lesson_node(self):
        return self.learning_object.material.course_package_lesson_node

    def __str__(self):
        return f"[{self.variant}] {self.learning_object.title}"


def standard_bundle_for(learning_object):
    """The objects the Standard version of this concept is taught as.

    A concept holds a bundle per PDF, so its Standard version is every object of
    the Standard bundle in document order. An object outside a concept -- or one
    whose concept is served by another PDF -- is a bundle of itself.
    """
    if learning_object.group_id is None:
        return [learning_object]

    from .version_assignment import version_bundles

    objects = version_bundles(learning_object.group).get("STANDARD") or []
    if not any(item.id == learning_object.id for item in objects):
        return [learning_object]
    return objects


def audio_clip_for(learning_object):
    """The narration and clip generated for one object, or ``None``.

    Two playlists are searched. The lesson one holds the material's own
    teaching steps. The second holds the objects that supply *another*
    concept's version: they are marked as represented, so they are deliberately
    absent from the lesson playlist, and a version built only from that one
    would be served silently.
    """
    generated_json = learning_object.material.generated_json or {}
    sources = []
    if generated_json.get("lesson_audio_generated"):
        sources.append(generated_json.get("lesson_playlist", []))
    if generated_json.get("version_bundle_audio_generated"):
        sources.append(generated_json.get("version_bundle_playlist", []))

    for playlist in sources:
        for entry in playlist:
            if entry.get("learning_object_id") == learning_object.id:
                return {
                    "narration": entry.get("narration") or entry.get("text", ""),
                    "audio_url": entry.get("audio_url") or entry.get("audio", ""),
                }
    return None


def bundle_segments(objects):
    """One ``{"text", "audio_url"}`` segment per object, in bundle order.

    An object with no clip yet still gets a segment carrying its own text, so
    a reader never loses part of a version while the audio is being made.
    """
    segments = []
    for item in objects:
        clip = audio_clip_for(item) or {}
        segments.append({
            "text": (clip.get("narration") or item.content or "").strip(),
            "audio_url": clip.get("audio_url") or "",
            # Which object the clip speaks for, so a player can label it.
            "title": item.title or "",
        })
    return segments


def standard_variant_for(learning_object):
    """The Standard version of this object's concept: its whole bundle, joined.

    ``None`` until the narration exists, which is what tells a caller to fall
    back to the source text.
    """
    objects = standard_bundle_for(learning_object)
    if not any(audio_clip_for(item) for item in objects):
        return None

    # Built from the very segments a reader is served, so the joined narration
    # and the segments can never tell a caller two different things.
    segments = bundle_segments(objects)
    return {
        "variant": "STANDARD",
        "narration": "\n".join(
            segment["text"] for segment in segments if segment["text"]
        ),
        "audio_url": next(
            (segment["audio_url"] for segment in segments if segment["audio_url"]), ""
        ),
    }


