# Generated by Django 5.2.17 on 2026-09-04 15:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('p_guess', models.FloatField(default=0.2, help_text="P(correct answer | learner doesn't actually know it).", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('p_slip', models.FloatField(default=0.1, help_text='P(wrong answer | learner does know it).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('p_learn', models.FloatField(default=0.15, help_text='P(learner transitions from not-knowing to knowing after one question).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mastery_ceiling', models.FloatField(default=0.99, help_text='Upper cap applied to the computed mastery score.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('starting_mastery', models.FloatField(default=0.3, help_text='Mastery a learner starts a new lesson node with.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('default_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Difficulty used to pick the first question for a bloom tier.', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adaptive engine weights',
                'verbose_name_plural': 'Adaptive engine weights',
            },
        ),
    ]
