# Generated by Django 5.2.17 on 2026-10-04 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptiveconfig',
            name='calibration_margin',
            field=models.FloatField(default=0.15, help_text='how close the systems guess of a students score must be before we can trust it. So basically the guess must be within 15 points of the students real score, measured 95% sure. Until then----student is still calibrating.', validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='adaptiveconfig',
            name='p_guess_true_false',
            field=models.FloatField(default=0.45, help_text="Probability of(correct answer | learner doesn't actually know it), for True/False questions.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='adaptiveconfig',
            name='prior_weight',
            field=models.PositiveSmallIntegerField(default=10, help_text="Blends the score of a student on avg and their personal score into one estimate--tis cuz we cant trust a new student's score from only a few answers. The avg counts as this many answers.", validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='adaptiveconfig',
            name='p_guess',
            field=models.FloatField(default=0.2, help_text="Probability of(correct answer | learner doesn't actually know it), for multiple-choice questions.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='adaptiveconfig',
            name='p_learn',
            field=models.FloatField(default=0.15, help_text='Probability of(learner transitions from not-knowing to knowing after one question).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='adaptiveconfig',
            name='p_slip',
            field=models.FloatField(default=0.1, help_text='Probability of(wrong answer | learner does know it).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='adaptiveconfig',
            name='starting_mastery',
            field=models.FloatField(default=0.3, help_text='Population L0: Mastery a learner starts a new lesson node with.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
