# Generated by Django 5.2.17 on 2026-10-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_course_package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresponse',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question_format',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='variant',
            field=models.CharField(choices=[('standard', 'Standard'), ('simplified', 'Simplified'), ('elaborated', 'Elaborated')], default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='topicpackageprogress',
            name='regressed_positions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topicpackageprogress',
            name='return_to_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ConceptMastery',
        ),
    ]
