# Generated by Django 5.2.17 on 2026-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_course_package', '0002_studentresponse_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpackageprogress',
            name='pending_question_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
