# Generated by Django 5.2.16 on 2026-07-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0009_alter_courseoutline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_format', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False')], max_length=3)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, default='')),
                ('bloom_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], db_index=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10)),
                ('category', models.CharField(choices=[('Facts and Information', 'Facts and Information'), ('Meaning', 'Meaning'), ('Skills', 'Skills'), ('Outcome', 'Outcome')], max_length=30)),
                ('intended_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('difficulty_match', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='lessons.learningobject')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_generation_runs', to='lessons.learningmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='GenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='question_generation.generationrun')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='LearnerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(db_index=True, max_length=50)),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_generation.generatedquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['node', 'difficulty'], name='question_ge_node_id_893c00_idx'),
        ),
        migrations.AddIndex(
            model_name='generationevent',
            index=models.Index(fields=['run', 'seq'], name='question_ge_run_id_beb5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerresponse',
            index=models.Index(fields=['learner_id', 'question'], name='question_ge_learner_f2586b_idx'),
        ),
    ]
