# Generated by Django 5.2.17 on 2026-08-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_courseoutline_options_and_more'),
        ('question_generation', '0002_generationrun_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedquestion',
            name='difficulty_match',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='intended_difficulty',
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], db_index=True, default='draft', max_length=5),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='thinking_order',
            field=models.CharField(blank=True, choices=[('LOT', 'Lower Order Thinking'), ('HOT', 'Higher Order Thinking')], db_index=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='category',
            field=models.CharField(blank=True, choices=[('Facts and Information', 'Facts and Information'), ('Meaning', 'Meaning'), ('Skills', 'Skills'), ('Outcome', 'Outcome')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['node', 'thinking_order'], name='question_ge_node_id_850120_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['node', 'status'], name='question_ge_node_id_6f6ad8_idx'),
        ),
    ]
