# Generated by Django 5.2.17 on 2026-08-08 16:40

from django.db import migrations, models

# Same mapping as services/bloom_classifier.BLOOM_TO_THINKING_ORDER, inlined
# so this migration keeps working if that module changes later.
BLOOM_TO_THINKING_ORDER = {
    "remember": "LOT",
    "understand": "LOT",
    "apply": "LOT",
    "analyze": "HOT",
    "evaluate": "HOT",
    # "create" deliberately absent — see backfill below
}


def backfill_thinking_order(apps, schema_editor):
    """Carry existing questions over to the new labels.

    Rows already in the table came from finished runs, so they are final —
    without this they would all default to "draft" and vanish from every
    read path. Their thinking order is re-derived from the Bloom level that
    is already stored, so no re-classification is needed.

    Create-level rows are deleted: they only exist because an older pipeline
    let them through, and MCQ/TF cannot assess them.
    """
    GeneratedQuestion = apps.get_model("question_generation", "GeneratedQuestion")

    GeneratedQuestion.objects.filter(bloom_level="create").delete()

    for bloom_level, thinking_order in BLOOM_TO_THINKING_ORDER.items():
        GeneratedQuestion.objects.filter(bloom_level=bloom_level).update(
            thinking_order=thinking_order, status="final"
        )

    # anything with an unrecognised or empty bloom_level can't be mapped;
    # leave it unclassified but still final so it isn't silently lost
    GeneratedQuestion.objects.filter(thinking_order="").update(status="final")


def unbackfill(apps, schema_editor):
    """No-op: reversing only drops the columns this filled."""


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_outlinenode_related_info'),
        ('question_generation', '0002_generationrun_node'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generatedquestion',
            name='question_ge_node_id_893c00_idx',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='difficulty_match',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='intended_difficulty',
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], db_index=True, default='draft', max_length=5),
        ),
        migrations.AddField(
            model_name='generatedquestion',
            name='thinking_order',
            field=models.CharField(blank=True, choices=[('LOT', 'Lower Order Thinking'), ('HOT', 'Higher Order Thinking')], db_index=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='bloom_level',
            field=models.CharField(blank=True, choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='category',
            field=models.CharField(blank=True, choices=[('Facts and Information', 'Facts and Information'), ('Meaning', 'Meaning'), ('Skills', 'Skills'), ('Outcome', 'Outcome')], default='', max_length=30),
        ),
        migrations.RunPython(backfill_thinking_order, unbackfill),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['node', 'thinking_order'], name='question_ge_node_id_850120_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedquestion',
            index=models.Index(fields=['node', 'status'], name='question_ge_node_id_6f6ad8_idx'),
        ),
    ]
