# Generated by Django 5.2.17 on 2026-09-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_learningobject_represented_by'),
        ('question_generation', '0003_lot_hot_thinking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='outline_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_runs', to='lessons.outlinenode'),
        ),
        migrations.AlterField(
            model_name='generationrun',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_generation_runs', to='lessons.learningmaterial'),
        ),
    ]
