# Generated by Django 5.2.17 on 2026-09-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0004_generationrun_outline_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='kind',
            field=models.CharField(choices=[('extraction', 'PDF extraction'), ('questions', 'Question generation'), ('publish', 'Topic publish'), ('versions', 'Content version classification')], db_index=True, default='questions', max_length=12),
        ),
    ]
