# Generated by Django 5.2.17 on 2026-09-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0006_generatedquestion_generation_fingerprint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generatedquestion',
            name='question_ge_node_id_893c00_idx',
        ),
        migrations.RemoveField(
            model_name='generatedquestion',
            name='difficulty',
        ),
    ]
