# Generated by Django 5.2.17 on 2026-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0007_remove_unused_difficulty_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationevent',
            name='event_type',
            field=models.CharField(max_length=64),
        ),
    ]
