# Generated by Django 5.2.17 on 2026-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0008_alter_generationevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedquestion',
            name='source_text_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
