# Generated by Django 5.2.15 on 2026-07-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_id', models.CharField(db_index=True, default='default', max_length=80)),
                ('mastery', models.FloatField(default=0.3)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('tier_attempts', models.PositiveIntegerField(default=0)),
                ('current_variant', models.CharField(choices=[('NORMAL', 'Normal'), ('ELABORATED', 'Elaborated'), ('SIMPLIFIED', 'Simplified')], default='NORMAL', max_length=20)),
                ('current_bloom', models.CharField(choices=[('REMEMBER', 'Remember'), ('UNDERSTAND', 'Understand'), ('ANALYZE', 'Analyze')], default='REMEMBER', max_length=20)),
                ('reward', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(default=0)),
                ('reward', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
