# Generated by Django 5.2.17 on 2026-09-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0001_initial'),
        ('lessons', '0017_learningobject_grouping_content_hash'),
        ('question_generation', '0005_generationrun_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='current_generated_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='question_generation.generatedquestion'),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='current_step_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position (1-based) of the learning-path step the learner is on.', null=True),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='current_variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('simplified', 'Simplified'), ('elaborated', 'Elaborated')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='remediation_target_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='generated_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='question_generation.generatedquestion'),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lessons.question'),
        ),
        migrations.AddConstraint(
            model_name='studentresponse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('generated_question__isnull', True), ('question__isnull', False)), models.Q(('generated_question__isnull', False), ('question__isnull', True)), _connector='OR'), name='student_response_exactly_one_question_type'),
        ),
    ]
