# Generated by Django 5.2.15 on 2026-07-27 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adaptive', '0001_initial'),
        ('course', '0001_initial'),
        ('question_generation', '0002_generationrun_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='current_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemodule'),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='current_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonnode'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='learning_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='adaptive.learningstate'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_generation.generatedquestion'),
        ),
    ]
