# Generated by Django 5.2.17 on 2026-09-16 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0002_path_mode_fields'),
        ('lessons', '0017_learningobject_grouping_content_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningstate',
            name='remediation_target_position',
        ),
        migrations.AddField(
            model_name='learningstate',
            name='current_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.learningobject'),
        ),
        migrations.AddField(
            model_name='learningstate',
            name='remediation_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
