# Generated by Django 5.2.17 on 2026-08-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstate',
            name='current_bloom',
            field=models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], default='remember', max_length=20),
        ),
    ]
