# Generated by Django 5.2.17 on 2026-08-09 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0003_alter_learningstate_current_bloom'),
        ('question_generation', '0002_generationrun_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='question_generation.generatedquestion'),
        ),
    ]
