# Generated by Django 5.2.17 on 2026-09-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0003_remove_learningstate_remediation_target_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='remediated_positions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
