# Generated by Django 5.2.17 on 2026-09-17 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0004_learningstate_remediated_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='attempt_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
