# Generated by Django 5.2.17 on 2026-09-17 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0005_learningstate_attempt_started_at'),
        ('lessons', '0017_learningobject_grouping_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningstate',
            name='concept_mastery',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='action',
            field=models.CharField(blank=True, choices=[('next_question', 'Next question in the concept'), ('advance', 'Advanced'), ('resume', 'Resumed after a detour'), ('complete', 'Completed the course'), ('escalate_variant', 'Re-taught one explanation level along'), ('detour_prerequisite', 'Detoured through a prerequisite'), ('switch_source', "Switched to another source's explanation"), ('second_pass', 'Taught the concept again from the top'), ('retry', 'Asked again')], max_length=24),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='attempt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.learningobject'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='concept_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='concept_mastery_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='concept_mastery_before',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='next_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='lessons.learningobject'),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='next_step_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='next_variant',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='remediation_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='step_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='variant',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
