# Generated by Django 5.2.17 on 2026-10-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0007_ensure_enrollment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningstate',
            name='current_variant',
            field=models.CharField(choices=[('standard', 'Standard'), ('simplified', 'Simplified'), ('elaborated', 'Elaborated')], default='standard', max_length=10),
        ),
    ]
