# Generated by Django 5.2.17 on 2026-10-04 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Replace the old per-course LearningState with the calibration-phase
    student state: ConceptMastery, StudentBaseline and the Decision log."""

    dependencies = [
        ('adaptive', '0008_standard_variant'),
        # course/0009 rewrites the old LearningState rows, so it must run before they're dropped
        ('course', '0009_rename_normal_to_standard'),
        ('lessons', '0019_drop_merged_from'),
        ('mobile_course_package', '0002_studentresponse_attempt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The old engine's tables (test data only): dropped whole, child first,
        # instead of field by field -- SQLite can't remove fields a constraint uses.
        migrations.DeleteModel(
            name='StudentResponse',
        ),
        migrations.DeleteModel(
            name='LearningState',
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.CreateModel(
            name='ConceptMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.PositiveIntegerField()),
                ('mastery_score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'concept_id')},
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_correct', models.FloatField()),
                ('mastery_before', models.FloatField()),
                ('mastery_after', models.FloatField()),
                ('p_guess_used', models.FloatField()),
                ('baseline_ability', models.FloatField()),
                ('baseline_calibrated', models.BooleanField()),
                ('action', models.CharField(choices=[('next_question', 'Next question in the concept'), ('retry', 'Asked again'), ('escalate_variant', 'Re-taught with another explanation type'), ('regress', 'Sent back through a prerequisite concept'), ('resume', 'Resumed the topic after the prerequisite'), ('advance', 'Moved on to the next concept'), ('complete', 'Completed the topic')], max_length=24)),
                ('next_step_position', models.PositiveIntegerField(blank=True, null=True)),
                ('next_variant', models.CharField(blank=True, choices=[('standard', 'Standard'), ('simplified', 'Simplified'), ('elaborated', 'Elaborated')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='mobile_course_package.studentresponse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_responses_count', models.PositiveIntegerField(default=0)),
                ('total_correct_count', models.PositiveIntegerField(default=0)),
                ('first_attempts_count', models.PositiveIntegerField(default=0)),
                ('first_attempts_correct_count', models.PositiveIntegerField(default=0)),
                ('estimated_ability', models.FloatField()),
                ('estimated_l0', models.FloatField()),
                ('calibrated', models.BooleanField(default=False)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lessons.coursegroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
