# Generated by Django 5.2.17 on 2026-10-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0009_calibration_phase_student_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='action_probability',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='decision',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='decision',
            name='misses_on_question',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='decision',
            name='on_detour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decision',
            name='prerequisite_mastery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='questions_left_in_step',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='step_already_regressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decision',
            name='step_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
